### ISSUE TITLE
Arch PKGBUILD

### ISSUE THREAD

**Issue by Cyan903** [astier/xswm#11]
This software is pretty useful. I've been using it on a few of my Arch systems for a bit and I think it would be pretty convenient if there was a package for it on the AUR.

Would you mind if I created an AUR package for it? I was thinking of something along the lines of `xswm-git`. I can maintain it of course.

**Comment by astier** [comment]
Sure no problem. Go ahead if you are willing to maintain it. I was thinking of creating an AUR-package myself but don't really have time atm. Let me know if you do it. Did you encounter any bugs so far?

**Comment by Cyan903** [comment]
I have not encountered any bugs. It's been pretty stable so far. The `autostart.sh` functionality is very useful.

Here's the package. I only made a `-git` package since the repository isn't using tags and it's very easy to compile from source. The only additional thing this package does is install `xswm.desktop` to `/usr/share/xsessions` for use with login managers.

https://aur.archlinux.org/packages/xswm-git

**Comment by astier** [comment]
Cool thanks. I will use it in the future myself. I guess it can be closed now.
